name: Feature request
description: Propose an improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > This repository is archived and no longer active.
        > It remains public for study purposes only.
        > There is no guarantee of response, review, or fix.

  - type: input
    id: problem
    attributes:
      label: Problem statement
      placeholder: What pain point are you solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the desired behavior
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
